// Generated by CoffeeScript 1.12.2
(function() {
  var adjustSlide, adjustSlideCallback, initSlide, nextSlide, prevSlide, render, renderSlide, slideEl, slideIndex, slides, text;

  slides = [];

  slideEl = null;

  slideIndex = 0;

  text = '# Hello World';

  render = function() {
    var index;
    if (location.hash != null) {
      index = parseInt(location.hash.slice(1));
      return renderSlide(index);
    } else {
      return renderSlide(0);
    }
  };

  initSlide = function() {
    var html, i, len, parser, script, scripts;
    slideEl = document.getElementById('slide');
    scripts = document.getElementsByTagName('script');
    for (i = 0, len = scripts.length; i < len; i++) {
      script = scripts[i];
      if ('text/markdown' === script.getAttribute('type')) {
        text = script.innerHTML;
        break;
      }
    }
    parser = new HyperDown;
    html = parser.makeHtml(text);
    return slides = html.split('<hr>');
  };

  renderSlide = function(index) {
    index = parseInt(index);
    if (slides[index] == null) {
      index = 0;
    }
    slideIndex = index;
    slideEl.innerHTML = slides[index];
    return adjustSlide();
  };

  prevSlide = function() {
    var index;
    index = slideIndex > 0 ? slideIndex - 1 : 0;
    return location.hash = '#' + index;
  };

  nextSlide = function() {
    var index;
    index = slideIndex < slides.length - 2 ? slideIndex + 1 : slides.length - 1;
    return location.hash = '#' + index;
  };

  adjustSlide = function() {
    var img;
    img = slideEl.querySelector('img');
    if (img != null) {
      return img.onload = adjustSlideCallback;
    } else {
      return adjustSlideCallback();
    }
  };

  adjustSlideCallback = function() {
    var el, firstEl, height, i, len, ref;
    height = 0;
    firstEl = null;
    ref = slideEl.childNodes;
    for (i = 0, len = ref.length; i < len; i++) {
      el = ref[i];
      if (firstEl == null) {
        firstEl = el;
      }
      height += el.offsetHeight;
    }
    firstEl.style.marginTop = (window.innerHeight - height) / 2 + 'px';
    return document.title = ("[" + slideIndex + "] ") + firstEl.textContent;
  };

  document.addEventListener('DOMContentLoaded', function() {
    var resize;
    initSlide();
    render();
    window.onhashchange = render;
    (resize = function() {
      if (window.innerWidth / window.innerHeight > 4 / 3) {
        slideEl.style.width = window.innerHeight * 4 / 3 + 'px';
        slideEl.style.height = window.innerHeight + 'px';
      } else {
        slideEl.style.width = window.innerWidth + 'px';
        slideEl.style.height = window.innerWidth * 3 / 4 + 'px';
      }
      return adjustSlide();
    })();
    window.addEventListener('resize', resize);
    return window.onkeydown = function(e) {
      if (e.key != null) {
        if (e.key === 'ArrowLeft') {
          return prevSlide();
        } else if (e.key === 'ArrowRight') {
          return nextSlide();
        }
      } else if (e.keyIdentifier) {
        if (e.keyIdentifier === 'Left') {
          return prevSlide();
        } else if (e.keyIdentifier === 'Right') {
          return nextSlide();
        }
      }
    };
  });

}).call(this);
